services:
  study_redis:
    build: 
      dockerfile: Dockerfile
    ports:
      - "8081:80"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16